run:
  # Enables skipping of directories:
  # - vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
  skip-dirs:
    - internal/gopher-lua
    - internal/cronexpr

linters:
  enable:
    - gofmt

linters-settings:
  gofmt:
    simplify: false
