version: "2"
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/gopher-lua
      - internal/cronexpr
    rules:
        - path: _test\.go
          linters:
            - errcheck
  settings:
    staticcheck:
      checks: ["all", "-ST1005", "-ST1003", "-ST1019", "-ST1008", "-QF1001", "-QF1007", "-QF1003"]
