// aahaa_rpcs.ts
// ─────────────────────────────────────────────────────────────────────────────
// Aahaa engine — RPC surface. Platform-agnostic by construction: every RPC is
// plain JSON over Nakama's HTTP/gRPC/WebSocket RPC transport, so the SAME
// endpoints serve Unity iOS/Android/Desktop (IClient.RpcAsync), the web
// frontend (fetch → POST /v2/rpc/<id>), and any server-side orchestrator
// (http_key or service_token).
//
// USER RPCs (session auth):
//   quizverse_aahaa_get         → the user's current ranked Aahaa feed
//                                 (?generate=true to recompute on the spot)
//   quizverse_aahaa_react       → shown|clicked|dismissed|converted|muted loop
//   quizverse_aahaa_fact_pack   → the deducible Fact Pack + lineage
//                                 (Growth Dashboard tap-to-trace source)
//   quizverse_aahaa_profile_set → onboarding-set facts (exam goal, birthday,
//                                 preferred play time, interests)
//
// ADMIN / SERVICE RPCs (http_key OR service_token == SEEDQ_SERVICE_TOKEN):
//   quizverse_aahaa_generate_all → generate a feed for EVERY userID (cron batch)
//   quizverse_aahaa_validate     → No-Hallucination validator for LLM output
//   quizverse_aahaa_catalog      → catalog dump + live CTR stats per wow_id
//
// Cron wiring (same pattern as quizverse_seedq_ingest_tick):
//   curl -sS -X POST "http://nakama:7350/v2/rpc/quizverse_aahaa_generate_all?http_key=<key>&unwrap" \
//        -H 'Content-Type: application/json' \
//        -d '{"service_token":"<SEEDQ_SERVICE_TOKEN>","max_users":100}'

namespace Aahaa {

  function errPayload(code: number, message: string): string {
    return JSON.stringify({ ok: false, code: code, error: message });
  }

  function parse(payload: string): any {
    if (!payload || payload === "") return {};
    try { return JSON.parse(payload); } catch (e) {
      throw new Error(JSON.stringify({ code: 3, message: "payload must be valid JSON" }));
    }
  }

  function isAdminOrService(ctx: nkruntime.Context, data: any): boolean {
    return SeedQ.isHttpKeyAdmin(ctx, data);
  }

  // ── quizverse_aahaa_get ─────────────────────────────────────────────────────
  // Request:  { generate?: boolean }
  // Response: { ok, feed: GeneratedWow[], rating_prompt_suppressed, generated_ms }
  //
  // The feed is pre-generated by the cron batch; `generate:true` forces a
  // fresh compute (use after quiz completion so post-quiz wows reflect the
  // quiz that just ended).
  function rpcGet(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string): string {
    var data = parse(payload);
    if (!ctx.userId) return errPayload(16, "session required");

    var feedDoc = SeedQ.readUser(nk, AahaaEngine.COLL_FEED, AahaaEngine.KEY_FEED, ctx.userId);
    var stale = !feedDoc || (Date.now() - (feedDoc.generated_ms || 0)) > 6 * 3600 * 1000;
    if (data.generate === true || stale) {
      var res = AahaaEngine.generateForUser(ctx, nk, logger, ctx.userId);
      return JSON.stringify({
        ok: true,
        generated_now: true,
        feed: res.feed,
        rating_prompt_suppressed: res.rating_prompt_suppressed,
        generated_ms: Date.now(),
        module_version: AahaaEngine.MODULE_VERSION
      });
    }
    return JSON.stringify({
      ok: true,
      generated_now: false,
      feed: feedDoc.feed || [],
      rating_prompt_suppressed: !!feedDoc.rating_prompt_suppressed,
      generated_ms: feedDoc.generated_ms || 0,
      module_version: AahaaEngine.MODULE_VERSION
    });
  }

  // ── quizverse_aahaa_react ───────────────────────────────────────────────────
  // Request:  { wow_id, action: "shown"|"clicked"|"dismissed"|"converted"|"muted", fullscreen? }
  // Response: { ok }
  function rpcReact(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string): string {
    var data = parse(payload);
    if (!ctx.userId) return errPayload(16, "session required");
    var wowId = ("" + (data.wow_id || "")).slice(0, 64);
    var action = ("" + (data.action || "")).toLowerCase();
    if (!wowId) return errPayload(3, "wow_id required");
    var allowed = ["shown", "clicked", "dismissed", "converted", "muted"];
    if (allowed.indexOf(action) < 0) return errPayload(3, "action must be one of " + allowed.join("|"));

    if (action === "muted") {
      AahaaEngine.muteWow(nk, ctx.userId, wowId);
    } else {
      AahaaEngine.recordReaction(nk, wowId, action);
      if (action === "shown") AahaaEngine.markFired(nk, ctx.userId, wowId, data.fullscreen === true);
    }
    return JSON.stringify({ ok: true, wow_id: wowId, action: action });
  }

  // ── quizverse_aahaa_fact_pack ───────────────────────────────────────────────
  // Request:  {} (session)  OR  { service_token, user_id } (LLM narration
  //           surfaces fetch the fact pack server-side before prompting).
  // Response: { ok, facts, constraints } — `constraints` mirrors §7.1 of
  //           CATALOG-DEDUCIBLE_INSIGHTS.md and should be forwarded verbatim
  //           into the LLM prompt.
  function rpcFactPack(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string): string {
    var data = parse(payload);
    var userId = ctx.userId || "";
    if (!userId) {
      if (!isAdminOrService(ctx, data)) return errPayload(16, "session or http_key+user_id required");
      userId = "" + (data.user_id || "");
      if (!userId) return errPayload(3, "user_id required for service caller");
    }
    var facts = AahaaFacts.buildFactPack(ctx, nk, logger, userId);
    return JSON.stringify({
      ok: true,
      facts: facts,
      constraints: {
        max_words: 60,
        must_use_at_least_one_fact: true,
        must_not_invent_numbers: true,
        must_not_claim_emotion: true,
        must_cite_each_numeric_claim: true
      }
    });
  }

  // ── quizverse_aahaa_profile_set ─────────────────────────────────────────────
  // Onboarding-set facts — the user typed them, we store them verbatim.
  // Request: { target_exam_id?, exam_date_iso?, preferred_play_time?,
  //            interests?: string[], birthday? ("YYYY-MM-DD") }
  function rpcProfileSet(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string): string {
    var data = parse(payload);
    if (!ctx.userId) return errPayload(16, "session required");

    var profile = AahaaEngine.readProfile(nk, ctx.userId);
    var ob = profile.onboarding;
    var changed: string[] = [];

    if (data.target_exam_id !== undefined) { ob.target_exam_id = ("" + data.target_exam_id).slice(0, 40); changed.push("target_exam_id"); }
    if (data.exam_date_iso !== undefined) { ob.exam_date_iso = ("" + data.exam_date_iso).slice(0, 24); changed.push("exam_date_iso"); }
    if (data.preferred_play_time !== undefined) { ob.preferred_play_time = ("" + data.preferred_play_time).slice(0, 24); changed.push("preferred_play_time"); }
    if (data.interests !== undefined && data.interests && data.interests.length !== undefined) {
      var ints: string[] = [];
      for (var i = 0; i < data.interests.length && i < 20; i++) ints.push(("" + data.interests[i]).slice(0, 40));
      ob.interests = ints; changed.push("interests");
    }
    if (data.birthday !== undefined) {
      ob.birthday = ("" + data.birthday).slice(0, 10);
      ob.birthday_set_ms = Date.now(); // anti-fake guard for wow.s.birthday_quiz
      changed.push("birthday");
    }

    AahaaEngine.writeProfile(nk, ctx.userId, profile);
    return JSON.stringify({ ok: true, changed: changed, onboarding: ob });
  }

  // ── quizverse_aahaa_generate_all (admin/service, cron) ──────────────────────
  // Request: { service_token?, max_users?, reset_cursor? }
  function rpcGenerateAll(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string): string {
    var data = parse(payload);
    if (!isAdminOrService(ctx, data)) return errPayload(7, "admin or service_token required");
    var maxUsers = SeedQ.clampInt(data.max_users, 1, 500, 100);
    var res = AahaaEngine.generateAll(ctx, nk, logger, maxUsers, data.reset_cursor === true);
    logger.info("[Aahaa] generate_all processed=" + res.processed + " errors=" + res.errors + " exhausted=" + res.cursor_exhausted);
    return JSON.stringify({ ok: true, batch: res, module_version: AahaaEngine.MODULE_VERSION });
  }

  // ── quizverse_aahaa_validate (admin/service) ────────────────────────────────
  // The No-Hallucination gate for LLM narration. Callers: AI Host / Fortune
  // Teller / Tutor services, web prod-canary middleware, CI fixtures.
  // Request: { service_token?, text, surface?, max_words?,
  //            user_id? (build fact pack) | facts? (inline fact pack) }
  function rpcValidate(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string): string {
    var data = parse(payload);
    if (!isAdminOrService(ctx, data)) return errPayload(7, "admin or service_token required");
    var text = "" + (data.text || "");
    if (!text) return errPayload(3, "text required");

    var facts: any = data.facts || null;
    if (!facts && data.user_id) {
      facts = AahaaFacts.buildFactPack(ctx, nk, logger, "" + data.user_id);
    }
    if (!facts) return errPayload(3, "facts or user_id required");

    var res = AahaaValidator.validate(text, facts, { surface: data.surface, max_words: data.max_words });
    return JSON.stringify({ ok: true, validation: res });
  }

  // ── quizverse_aahaa_catalog (admin/service) ─────────────────────────────────
  // Live-ops observability: the full catalog + rolling CTR stats per wow_id.
  function rpcCatalog(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string): string {
    var data = parse(payload);
    if (!isAdminOrService(ctx, data)) return errPayload(7, "admin or service_token required");

    var stats = SeedQ.readSystem(nk, AahaaEngine.COLL_STATS, "stats") || { wows: {} };
    var entries = AahaaCatalog.catalog();
    var out: any[] = [];
    for (var i = 0; i < entries.length; i++) {
      var e = entries[i];
      var w = (stats.wows && stats.wows[e.wow_id]) || { shown: 0, clicked: 0, dismissed: 0 };
      out.push({
        wow_id: e.wow_id, tier: e.tier, surface: e.surface,
        copy_template: e.copy_template, cta_action_id: e.cta_action_id,
        loop_event: e.loop_event, mechanic: e.mechanic,
        priority_class: e.priority_class, celebratory: e.celebratory,
        fullscreen: e.fullscreen, cooldown_days: e.cooldown_days,
        data_sources: e.data_sources,
        stats: { shown: w.shown | 0, clicked: w.clicked | 0, dismissed: w.dismissed | 0,
                 ctr: (w.shown | 0) > 0 ? Math.round(((w.clicked | 0) / w.shown) * 1000) / 1000 : null }
      });
    }
    var batch = SeedQ.readSystem(nk, AahaaEngine.COLL_BATCH, "state") || {};
    return JSON.stringify({
      ok: true, catalog: out, catalog_size: out.length,
      batch_state: { runs: batch.runs || 0, users_done_total: batch.users_done_total || 0, last_run_ms: batch.last_run_ms || 0 },
      module_version: AahaaEngine.MODULE_VERSION
    });
  }

  // ── Registration ────────────────────────────────────────────────────────────
  export function register(initializer: nkruntime.Initializer): void {
    initializer.registerRpc("quizverse_aahaa_get", rpcGet);
    initializer.registerRpc("quizverse_aahaa_react", rpcReact);
    initializer.registerRpc("quizverse_aahaa_fact_pack", rpcFactPack);
    initializer.registerRpc("quizverse_aahaa_profile_set", rpcProfileSet);
    initializer.registerRpc("quizverse_aahaa_generate_all", rpcGenerateAll);
    initializer.registerRpc("quizverse_aahaa_validate", rpcValidate);
    initializer.registerRpc("quizverse_aahaa_catalog", rpcCatalog);
  }
}
