// Code generated by protoc-gen-go. DO NOT EDIT.
// source: console/console.proto

/*
Package console is a generated protocol buffer package.

It is generated from these files:
	console/console.proto

It has these top-level messages:
	AccountExport
	AccountIdRequest
	AuthenticateRequest
	Session
*/
package console

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import nakama_api "github.com/heroiclabs/nakama/api"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// An export of all information stored for a user account.
type AccountExport struct {
	// The user's account details.
	Account *nakama_api.Account `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	// The user's storage.
	Objects []*nakama_api.StorageObject `protobuf:"bytes,2,rep,name=objects" json:"objects,omitempty"`
	// The user's friends.
	Friends []*nakama_api.Friend `protobuf:"bytes,3,rep,name=friends" json:"friends,omitempty"`
	// The user's groups.
	Groups []*nakama_api.Group `protobuf:"bytes,4,rep,name=groups" json:"groups,omitempty"`
	// The user's notifications.
	Notifications []*nakama_api.Notification `protobuf:"bytes,5,rep,name=notifications" json:"notifications,omitempty"`
}

func (m *AccountExport) Reset()                    { *m = AccountExport{} }
func (m *AccountExport) String() string            { return proto.CompactTextString(m) }
func (*AccountExport) ProtoMessage()               {}
func (*AccountExport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccountExport) GetAccount() *nakama_api.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *AccountExport) GetObjects() []*nakama_api.StorageObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *AccountExport) GetFriends() []*nakama_api.Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *AccountExport) GetGroups() []*nakama_api.Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *AccountExport) GetNotifications() []*nakama_api.Notification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

// *
// The identifier for a user account.
type AccountIdRequest struct {
	// The unique identifier of the user account.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *AccountIdRequest) Reset()                    { *m = AccountIdRequest{} }
func (m *AccountIdRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountIdRequest) ProtoMessage()               {}
func (*AccountIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccountIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// *
// Authenticate against the server with username+password.
type AuthenticateRequest struct {
	// The username of the user.
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	// The password of the user.
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *AuthenticateRequest) Reset()                    { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()               {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthenticateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// *
// A user's session used to authenticate messages.
type Session struct {
	// Authentication credentials.
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountExport)(nil), "nakama.console.AccountExport")
	proto.RegisterType((*AccountIdRequest)(nil), "nakama.console.AccountIdRequest")
	proto.RegisterType((*AuthenticateRequest)(nil), "nakama.console.AuthenticateRequest")
	proto.RegisterType((*Session)(nil), "nakama.console.Session")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Console service

type ConsoleClient interface {
	// Delete all information stored for a user account.
	DeleteAccount(ctx context.Context, in *AccountIdRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Export all information stored about a user account.
	ExportAccount(ctx context.Context, in *AccountIdRequest, opts ...grpc.CallOption) (*AccountExport, error)
	// Authenticate a user with username+password.
	Login(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*Session, error)
}

type consoleClient struct {
	cc *grpc.ClientConn
}

func NewConsoleClient(cc *grpc.ClientConn) ConsoleClient {
	return &consoleClient{cc}
}

func (c *consoleClient) DeleteAccount(ctx context.Context, in *AccountIdRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/nakama.console.Console/DeleteAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) ExportAccount(ctx context.Context, in *AccountIdRequest, opts ...grpc.CallOption) (*AccountExport, error) {
	out := new(AccountExport)
	err := grpc.Invoke(ctx, "/nakama.console.Console/ExportAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) Login(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := grpc.Invoke(ctx, "/nakama.console.Console/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Console service

type ConsoleServer interface {
	// Delete all information stored for a user account.
	DeleteAccount(context.Context, *AccountIdRequest) (*google_protobuf1.Empty, error)
	// Export all information stored about a user account.
	ExportAccount(context.Context, *AccountIdRequest) (*AccountExport, error)
	// Authenticate a user with username+password.
	Login(context.Context, *AuthenticateRequest) (*Session, error)
}

func RegisterConsoleServer(s *grpc.Server, srv ConsoleServer) {
	s.RegisterService(&_Console_serviceDesc, srv)
}

func _Console_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nakama.console.Console/DeleteAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).DeleteAccount(ctx, req.(*AccountIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_ExportAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).ExportAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nakama.console.Console/ExportAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).ExportAccount(ctx, req.(*AccountIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nakama.console.Console/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).Login(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Console_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nakama.console.Console",
	HandlerType: (*ConsoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteAccount",
			Handler:    _Console_DeleteAccount_Handler,
		},
		{
			MethodName: "ExportAccount",
			Handler:    _Console_ExportAccount_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Console_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "console/console.proto",
}

func init() { proto.RegisterFile("console/console.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x4f, 0xd4, 0x40,
	0x14, 0xc7, 0xb3, 0x45, 0x58, 0x1d, 0xb2, 0x04, 0x07, 0x90, 0xb2, 0x48, 0xa8, 0xc5, 0x18, 0xdc,
	0x40, 0xc7, 0x94, 0x1b, 0x07, 0xe3, 0x82, 0x68, 0x48, 0x14, 0x4d, 0xf1, 0xe4, 0xc5, 0x74, 0xdb,
	0x47, 0xb7, 0xd0, 0x9d, 0x57, 0x66, 0xa6, 0xa0, 0x31, 0x5c, 0x3c, 0x7b, 0xd2, 0xcf, 0xe5, 0xc9,
	0xaf, 0xe0, 0xc9, 0x2f, 0xe0, 0xd5, 0xb4, 0x33, 0xc5, 0xc2, 0x46, 0xe3, 0x61, 0xd3, 0xcc, 0xfc,
	0x7f, 0xff, 0xf7, 0xde, 0xcc, 0xfe, 0x87, 0x2c, 0x44, 0xc8, 0x25, 0x66, 0xc0, 0xcc, 0xd7, 0xcb,
	0x05, 0x2a, 0xa4, 0x33, 0x3c, 0x3c, 0x09, 0x47, 0xa1, 0x67, 0x76, 0xbb, 0xbd, 0x24, 0x55, 0xc3,
	0x62, 0xe0, 0x45, 0x38, 0x62, 0x43, 0x10, 0x98, 0x46, 0x59, 0x38, 0x90, 0x4c, 0x53, 0x2c, 0xcc,
	0xd3, 0xf2, 0xa7, 0xbd, 0xdd, 0xbb, 0x09, 0x62, 0x92, 0x81, 0xde, 0xe5, 0x1c, 0x55, 0xa8, 0x52,
	0xe4, 0xd2, 0xa8, 0xcb, 0x46, 0xad, 0x56, 0x83, 0xe2, 0x88, 0xc1, 0x28, 0x57, 0x1f, 0x8c, 0xb8,
	0x51, 0x7d, 0xa2, 0xcd, 0x04, 0xf8, 0xa6, 0x3c, 0x0f, 0x93, 0x04, 0x04, 0xc3, 0xbc, 0xb2, 0x8f,
	0x97, 0x72, 0x3f, 0x5b, 0xa4, 0xd3, 0x8f, 0x22, 0x2c, 0xb8, 0xda, 0x7b, 0x9f, 0xa3, 0x50, 0x74,
	0x93, 0xb4, 0x43, 0xbd, 0x61, 0xb7, 0x9c, 0xd6, 0xfa, 0xb4, 0x3f, 0xe7, 0x99, 0x83, 0x94, 0xe3,
	0x19, 0x36, 0xa8, 0x19, 0xba, 0x45, 0xda, 0x38, 0x38, 0x86, 0x48, 0x49, 0xdb, 0x72, 0x26, 0xd6,
	0xa7, 0xfd, 0xa5, 0x26, 0x7e, 0xa8, 0x50, 0x84, 0x09, 0xbc, 0xaa, 0x88, 0xa0, 0x26, 0xe9, 0x06,
	0x69, 0x1f, 0x89, 0x14, 0x78, 0x2c, 0xed, 0x89, 0xca, 0x44, 0x9b, 0xa6, 0x67, 0x95, 0x14, 0xd4,
	0x08, 0x7d, 0x48, 0xa6, 0x12, 0x81, 0x45, 0x2e, 0xed, 0x1b, 0x15, 0x7c, 0xbb, 0x09, 0x3f, 0x2f,
	0x95, 0xc0, 0x00, 0xf4, 0x31, 0xe9, 0x70, 0x54, 0xe9, 0x51, 0x1a, 0xe9, 0x53, 0xda, 0x93, 0x95,
	0xc3, 0x6e, 0x3a, 0x0e, 0x1a, 0x40, 0x70, 0x15, 0x77, 0x5d, 0x32, 0x6b, 0x4e, 0xb8, 0x1f, 0x07,
	0x70, 0x5a, 0x80, 0x54, 0x74, 0x86, 0x58, 0x69, 0x5c, 0xdd, 0xc5, 0xad, 0xc0, 0x4a, 0x63, 0xf7,
	0x25, 0x99, 0xeb, 0x17, 0x6a, 0x08, 0x5c, 0x95, 0x36, 0xa8, 0xb1, 0x2e, 0xb9, 0x59, 0x48, 0x10,
	0x3c, 0x1c, 0x81, 0x81, 0x2f, 0xd7, 0xa5, 0x96, 0x87, 0x52, 0x9e, 0xa3, 0x88, 0x6d, 0x4b, 0x6b,
	0xf5, 0xda, 0x5d, 0x25, 0xed, 0x43, 0x90, 0x32, 0x45, 0x4e, 0xe7, 0xc9, 0xa4, 0xc2, 0x13, 0xe0,
	0xc6, 0xaf, 0x17, 0xfe, 0x37, 0x8b, 0xb4, 0x77, 0x75, 0x86, 0x68, 0x44, 0x3a, 0x4f, 0x21, 0x03,
	0x05, 0x66, 0x4a, 0xea, 0x78, 0x57, 0x53, 0xe6, 0x5d, 0x1f, 0xbf, 0x7b, 0xc7, 0xd3, 0x69, 0xf1,
	0xea, 0xb4, 0x78, 0x7b, 0x65, 0x5a, 0x5c, 0xfb, 0xd3, 0xf7, 0x1f, 0x5f, 0x2d, 0xda, 0x9b, 0x65,
	0x67, 0x3e, 0x33, 0xff, 0x26, 0xfb, 0x98, 0xc6, 0x17, 0xf4, 0x94, 0x74, 0x74, 0x16, 0xfe, 0xbf,
	0xc9, 0xca, 0x5f, 0x08, 0x5d, 0xc7, 0x5d, 0xad, 0x7a, 0x2d, 0xd1, 0xc5, 0xeb, 0xbd, 0x18, 0xe8,
	0xd0, 0x1d, 0x93, 0xc9, 0x17, 0x98, 0xa4, 0x9c, 0xae, 0x8d, 0x15, 0x1a, 0xbf, 0xea, 0xee, 0xe2,
	0x75, 0xc8, 0x5c, 0xa0, 0xbb, 0x56, 0xf5, 0x59, 0x71, 0xed, 0x66, 0x9f, 0xb0, 0x51, 0x61, 0xbb,
	0xd5, 0xdb, 0xf9, 0xd5, 0xfa, 0xd2, 0xff, 0xd9, 0xa2, 0x17, 0x64, 0xe1, 0xa0, 0xaa, 0xe2, 0x98,
	0x2a, 0x4e, 0xff, 0xf5, 0xbe, 0x73, 0xe6, 0xbb, 0xef, 0xc8, 0xbd, 0x37, 0x43, 0x70, 0x8c, 0x58,
	0xf6, 0x47, 0x21, 0x9d, 0x07, 0xce, 0x2e, 0x72, 0x25, 0xd2, 0x41, 0xa1, 0x50, 0x48, 0x7a, 0x7f,
	0xa8, 0x54, 0x2e, 0xb7, 0x19, 0xfb, 0xd7, 0xa3, 0xee, 0xce, 0x0f, 0x21, 0xcb, 0xf0, 0xc9, 0x1f,
	0xa1, 0xe4, 0xfc, 0x09, 0xdf, 0x7b, 0xd4, 0x6b, 0xb5, 0xfc, 0xd9, 0x30, 0xcf, 0x33, 0x13, 0x3d,
	0x76, 0x2c, 0x91, 0x6f, 0x8f, 0xed, 0x88, 0x1d, 0xb2, 0x66, 0x06, 0x91, 0x20, 0xce, 0x40, 0x5c,
	0x0e, 0x1b, 0x63, 0x54, 0x8c, 0x80, 0xeb, 0xd7, 0x4c, 0x97, 0xeb, 0x71, 0xae, 0xb6, 0x62, 0x31,
	0x46, 0xf2, 0x6d, 0xdb, 0x78, 0x06, 0x53, 0x55, 0x04, 0xb6, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xba, 0xdd, 0x43, 0x43, 0xb1, 0x04, 0x00, 0x00,
}
