// ISO 3166-1 lookup table for the dashboard world map.
//
// world-atlas `countries-110m.json` features are keyed by ISO 3166-1 *numeric*
// code (e.g. "840" = United States). Our event geo is captured as ISO 3166-1
// *alpha-2* (e.g. "US", from GeoTier). This table bridges the two so the
// choropleth can colour a country by the active-user count we measured.

export interface IsoCountry {
  a2: string;
  name: string;
}

// numeric code (string, as it appears in the topojson `geo.id`) → { a2, name }
export const ISO_NUMERIC: Record<string, IsoCountry> = {
  "004": { a2: "AF", name: "Afghanistan" },
  "008": { a2: "AL", name: "Albania" },
  "012": { a2: "DZ", name: "Algeria" },
  "024": { a2: "AO", name: "Angola" },
  "032": { a2: "AR", name: "Argentina" },
  "051": { a2: "AM", name: "Armenia" },
  "036": { a2: "AU", name: "Australia" },
  "040": { a2: "AT", name: "Austria" },
  "031": { a2: "AZ", name: "Azerbaijan" },
  "044": { a2: "BS", name: "Bahamas" },
  "050": { a2: "BD", name: "Bangladesh" },
  "112": { a2: "BY", name: "Belarus" },
  "056": { a2: "BE", name: "Belgium" },
  "084": { a2: "BZ", name: "Belize" },
  "204": { a2: "BJ", name: "Benin" },
  "064": { a2: "BT", name: "Bhutan" },
  "068": { a2: "BO", name: "Bolivia" },
  "070": { a2: "BA", name: "Bosnia and Herzegovina" },
  "072": { a2: "BW", name: "Botswana" },
  "076": { a2: "BR", name: "Brazil" },
  "096": { a2: "BN", name: "Brunei" },
  "100": { a2: "BG", name: "Bulgaria" },
  "854": { a2: "BF", name: "Burkina Faso" },
  "108": { a2: "BI", name: "Burundi" },
  "116": { a2: "KH", name: "Cambodia" },
  "120": { a2: "CM", name: "Cameroon" },
  "124": { a2: "CA", name: "Canada" },
  "140": { a2: "CF", name: "Central African Republic" },
  "148": { a2: "TD", name: "Chad" },
  "152": { a2: "CL", name: "Chile" },
  "156": { a2: "CN", name: "China" },
  "170": { a2: "CO", name: "Colombia" },
  "178": { a2: "CG", name: "Congo" },
  "180": { a2: "CD", name: "DR Congo" },
  "188": { a2: "CR", name: "Costa Rica" },
  "384": { a2: "CI", name: "Côte d'Ivoire" },
  "191": { a2: "HR", name: "Croatia" },
  "192": { a2: "CU", name: "Cuba" },
  "196": { a2: "CY", name: "Cyprus" },
  "203": { a2: "CZ", name: "Czechia" },
  "208": { a2: "DK", name: "Denmark" },
  "262": { a2: "DJ", name: "Djibouti" },
  "214": { a2: "DO", name: "Dominican Republic" },
  "218": { a2: "EC", name: "Ecuador" },
  "818": { a2: "EG", name: "Egypt" },
  "222": { a2: "SV", name: "El Salvador" },
  "226": { a2: "GQ", name: "Equatorial Guinea" },
  "232": { a2: "ER", name: "Eritrea" },
  "233": { a2: "EE", name: "Estonia" },
  "748": { a2: "SZ", name: "Eswatini" },
  "231": { a2: "ET", name: "Ethiopia" },
  "238": { a2: "FK", name: "Falkland Islands" },
  "242": { a2: "FJ", name: "Fiji" },
  "246": { a2: "FI", name: "Finland" },
  "250": { a2: "FR", name: "France" },
  "266": { a2: "GA", name: "Gabon" },
  "270": { a2: "GM", name: "Gambia" },
  "268": { a2: "GE", name: "Georgia" },
  "276": { a2: "DE", name: "Germany" },
  "288": { a2: "GH", name: "Ghana" },
  "300": { a2: "GR", name: "Greece" },
  "304": { a2: "GL", name: "Greenland" },
  "320": { a2: "GT", name: "Guatemala" },
  "324": { a2: "GN", name: "Guinea" },
  "624": { a2: "GW", name: "Guinea-Bissau" },
  "328": { a2: "GY", name: "Guyana" },
  "332": { a2: "HT", name: "Haiti" },
  "340": { a2: "HN", name: "Honduras" },
  "348": { a2: "HU", name: "Hungary" },
  "352": { a2: "IS", name: "Iceland" },
  "356": { a2: "IN", name: "India" },
  "360": { a2: "ID", name: "Indonesia" },
  "364": { a2: "IR", name: "Iran" },
  "368": { a2: "IQ", name: "Iraq" },
  "372": { a2: "IE", name: "Ireland" },
  "376": { a2: "IL", name: "Israel" },
  "380": { a2: "IT", name: "Italy" },
  "388": { a2: "JM", name: "Jamaica" },
  "392": { a2: "JP", name: "Japan" },
  "400": { a2: "JO", name: "Jordan" },
  "398": { a2: "KZ", name: "Kazakhstan" },
  "404": { a2: "KE", name: "Kenya" },
  "408": { a2: "KP", name: "North Korea" },
  "410": { a2: "KR", name: "South Korea" },
  "414": { a2: "KW", name: "Kuwait" },
  "417": { a2: "KG", name: "Kyrgyzstan" },
  "418": { a2: "LA", name: "Laos" },
  "428": { a2: "LV", name: "Latvia" },
  "422": { a2: "LB", name: "Lebanon" },
  "426": { a2: "LS", name: "Lesotho" },
  "430": { a2: "LR", name: "Liberia" },
  "434": { a2: "LY", name: "Libya" },
  "440": { a2: "LT", name: "Lithuania" },
  "442": { a2: "LU", name: "Luxembourg" },
  "807": { a2: "MK", name: "North Macedonia" },
  "450": { a2: "MG", name: "Madagascar" },
  "454": { a2: "MW", name: "Malawi" },
  "458": { a2: "MY", name: "Malaysia" },
  "466": { a2: "ML", name: "Mali" },
  "478": { a2: "MR", name: "Mauritania" },
  "484": { a2: "MX", name: "Mexico" },
  "498": { a2: "MD", name: "Moldova" },
  "496": { a2: "MN", name: "Mongolia" },
  "499": { a2: "ME", name: "Montenegro" },
  "504": { a2: "MA", name: "Morocco" },
  "508": { a2: "MZ", name: "Mozambique" },
  "104": { a2: "MM", name: "Myanmar" },
  "516": { a2: "NA", name: "Namibia" },
  "524": { a2: "NP", name: "Nepal" },
  "528": { a2: "NL", name: "Netherlands" },
  "540": { a2: "NC", name: "New Caledonia" },
  "554": { a2: "NZ", name: "New Zealand" },
  "558": { a2: "NI", name: "Nicaragua" },
  "562": { a2: "NE", name: "Niger" },
  "566": { a2: "NG", name: "Nigeria" },
  "578": { a2: "NO", name: "Norway" },
  "512": { a2: "OM", name: "Oman" },
  "586": { a2: "PK", name: "Pakistan" },
  "591": { a2: "PA", name: "Panama" },
  "598": { a2: "PG", name: "Papua New Guinea" },
  "600": { a2: "PY", name: "Paraguay" },
  "604": { a2: "PE", name: "Peru" },
  "608": { a2: "PH", name: "Philippines" },
  "616": { a2: "PL", name: "Poland" },
  "620": { a2: "PT", name: "Portugal" },
  "634": { a2: "QA", name: "Qatar" },
  "642": { a2: "RO", name: "Romania" },
  "643": { a2: "RU", name: "Russia" },
  "646": { a2: "RW", name: "Rwanda" },
  "682": { a2: "SA", name: "Saudi Arabia" },
  "686": { a2: "SN", name: "Senegal" },
  "688": { a2: "RS", name: "Serbia" },
  "694": { a2: "SL", name: "Sierra Leone" },
  "703": { a2: "SK", name: "Slovakia" },
  "705": { a2: "SI", name: "Slovenia" },
  "090": { a2: "SB", name: "Solomon Islands" },
  "706": { a2: "SO", name: "Somalia" },
  "710": { a2: "ZA", name: "South Africa" },
  "728": { a2: "SS", name: "South Sudan" },
  "724": { a2: "ES", name: "Spain" },
  "144": { a2: "LK", name: "Sri Lanka" },
  "729": { a2: "SD", name: "Sudan" },
  "740": { a2: "SR", name: "Suriname" },
  "752": { a2: "SE", name: "Sweden" },
  "756": { a2: "CH", name: "Switzerland" },
  "760": { a2: "SY", name: "Syria" },
  "158": { a2: "TW", name: "Taiwan" },
  "762": { a2: "TJ", name: "Tajikistan" },
  "834": { a2: "TZ", name: "Tanzania" },
  "764": { a2: "TH", name: "Thailand" },
  "626": { a2: "TL", name: "Timor-Leste" },
  "768": { a2: "TG", name: "Togo" },
  "780": { a2: "TT", name: "Trinidad and Tobago" },
  "788": { a2: "TN", name: "Tunisia" },
  "792": { a2: "TR", name: "Turkey" },
  "795": { a2: "TM", name: "Turkmenistan" },
  "800": { a2: "UG", name: "Uganda" },
  "804": { a2: "UA", name: "Ukraine" },
  "784": { a2: "AE", name: "United Arab Emirates" },
  "826": { a2: "GB", name: "United Kingdom" },
  "840": { a2: "US", name: "United States" },
  "858": { a2: "UY", name: "Uruguay" },
  "860": { a2: "UZ", name: "Uzbekistan" },
  "548": { a2: "VU", name: "Vanuatu" },
  "862": { a2: "VE", name: "Venezuela" },
  "704": { a2: "VN", name: "Vietnam" },
  "732": { a2: "EH", name: "Western Sahara" },
  "887": { a2: "YE", name: "Yemen" },
  "894": { a2: "ZM", name: "Zambia" },
  "716": { a2: "ZW", name: "Zimbabwe" },
};

// alpha-2 → display name, derived from the numeric table above.
export const ISO_A2_NAME: Record<string, string> = (() => {
  const out: Record<string, string> = {};
  for (const num of Object.keys(ISO_NUMERIC)) {
    const c = ISO_NUMERIC[num];
    out[c.a2] = c.name;
  }
  return out;
})();

export function countryName(a2: string): string {
  return ISO_A2_NAME[(a2 || "").toUpperCase()] || a2 || "Unknown";
}

// Rough alpha-2 → regional indicator flag emoji (works for most clients).
export function flagEmoji(a2: string): string {
  const code = (a2 || "").toUpperCase();
  if (code.length !== 2 || !/^[A-Z]{2}$/.test(code)) return "🏳️";
  const base = 0x1f1e6;
  return String.fromCodePoint(
    base + (code.charCodeAt(0) - 65),
    base + (code.charCodeAt(1) - 65),
  );
}
